on:
  push:
    branches: [main]
    tags:
      - "*.*.*"
name: Release
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Process dataset
        run: uv run scripts/processing.py
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "output/countries.json"
